{
  "hash": "a4c4461c285e9d4722b675aac64dc5a7",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Our First RMarkdown File\"\ndate: \"4/21/2021\"\nformat:\n  html:\n    code-fold: true\nsearch: false\n---\n\n\n\nConsider the function $h(x) = \\sqrt{3-x}$. We would like to compute $h(-4)$ and $h(5)$. We can do this in two ways, (1) using R as a calculator or (2) define a function and then evaluate that function in R.\nTo compute $h(-4)$ we calculate $\\sqrt{3-(-4)}$.\n\n::: {.cell}\n\n```{.r .fold-show .cell-code}\nsqrt(3-(-4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.645751\n```\n\n\n:::\n:::\n\n\nTo compute $h(5)$ we calculate $\\sqrt{3-5}$.\n\n::: {.cell}\n\n```{.r .cell-code}\nsqrt(3-5)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in sqrt(3 - 5): NaNs produced\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] NaN\n```\n\n\n:::\n:::\n\n\nWe can also program the function $h$ in R and then evaluate.\n\n::: {.cell}\n\n```{.r .fold-show .cell-code}\nh <- function(x){\n  sqrt(3-x)\n}\n\nh(-4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.645751\n```\n\n\n:::\n\n```{.r .fold-show .cell-code}\nh(5)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in sqrt(3 - x): NaNs produced\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] NaN\n```\n\n\n:::\n:::\n\n\nWith either method we see $h(-4) \\approx 2.65$ and $h(5)$ is not defined.\n\n$~$  \n$~$  \n$~$  \n\nConsider the function $f(x) = \n\\begin{cases}\nx^3 & \\quad x < -1 \\\\  \n-2 & \\quad -1 < x < 4. \\\\  \n\\sqrt{x} & \\quad x \\geq 4\n\\end{cases}$\n\nEvaluate $f(-2)$. Since $-2 < -1$ we follow the first rule and $f(-2) = (-2)^3 = -8$. See the calculation in R below.\n\n::: {.cell}\n\n```{.r .fold-show .cell-code}\n(-2)^3\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -8\n```\n\n\n:::\n:::\n\n\nEvaluate $f(-0.5)$. Since $-1 < -0.5 < 4$ we follow the middle rule and $f(-0.5) = -2$. (No calculation required.)\n\nEvaluate $f(3)$. Since $-1 < 3 < 4$ we follow the middle rule and $f(3) = -2$. (No calculation required.)\n\nEvaluate $f(0)$. Since $-1 < 0 < 4$ we follow the middle rule and $f(0) = -2$. (No calculation required.)\n\nEvaluate $f(5.2)$. Since $5.2 \\geq 4$ we follow the last rule and $f(5.2) = \\sqrt{5.2} \\approx 2.28$. See the calculation in R below.\n\n::: {.cell}\n\n```{.r .fold-show .cell-code}\nsqrt(5.2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.280351\n```\n\n\n:::\n:::\n\n\nEvaluate $f(-1)$. Since $x=-1$ is not in the domain of $f$, $f(-1)$ is undefined.\n\nEvaluate $f(4)$. Since $4 \\geq 4$ we follow the last rule and $f(4) = \\sqrt{4} =2$. See the calculation in R below.\n\n::: {.cell}\n\n```{.r .fold-show .cell-code}\nsqrt(2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.414214\n```\n\n\n:::\n:::\n\n\nWe can also define our function in R and then evaluate. In the calculations below we see $f(-2)=-8$, $f(-0.5) = -2$, $f(3)=-2$, $f(0)$, $f(5.2) \\approx 2.28$, $f(-1)$ is not defined, and $f(4)=2$. Notice these are the same values above when we were using R as a calculator.\n\n::: {.cell}\n\n```{.r .cell-code}\nf <- function(x){\n  out <- rep(0,length(x))\n  out[(x < -1)] <- x[(x < -1)]^3\n  out[(x == -1)] <- NaN\n  out[(x > -1) & (x < 4)] <- -2 + 0*x[(x > -1) & (x < 4)]\n  out[(x >= 4)] <- sqrt(x[(x >= 4)])\n  \n  return(out)\n}\n\nf(-2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -8\n```\n\n\n:::\n\n```{.r .cell-code}\nf(-0.5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -2\n```\n\n\n:::\n\n```{.r .cell-code}\nf(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -2\n```\n\n\n:::\n\n```{.r .cell-code}\nf(0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -2\n```\n\n\n:::\n\n```{.r .cell-code}\nf(5.2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.280351\n```\n\n\n:::\n\n```{.r .cell-code}\nf(-1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] NaN\n```\n\n\n:::\n\n```{.r .cell-code}\nf(4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2\n```\n\n\n:::\n:::\n\n\nWe can also plot $f$ using R. A graph of $f$ is shown in the figure below. We create a list of inputs. We evaluate the function at each of the inputs in our list creating a list of outputs. Finally, we plot the inputs and the outputs and connect the ordered pairs or points with a curve.\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- seq(-2.5,36,0.01)\ny <- f(x)\npar(mfrow=c(1,1),mar=c(2.5,2.5,1,0.25))\nplot(x,y,type='l')\nabline(v=0,lty=3,col='gray')\nabline(h=0,lty=3,col='gray')\n```\n\n::: {.cell-output-display}\n![](Practice_RMarkdown_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n",
    "supporting": [
      "Practice_RMarkdown_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}